version: '3'

services:
  front:
    container_name: front
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:8080
    restart: always
    tty: true
    volumes:
      - ./src:/src